<?php

namespace Madisoft\StudentsBundle\Repository;

/**
 * SchoolGradeConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolGradeConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
