<?php

namespace Madisoft\StudentsBundle\Repository;

/**
 * SchoolSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
