<?php

namespace Madisoft\StudentsBundle\Repository;

/**
 * SchoolGradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolGradeRepository extends \Doctrine\ORM\EntityRepository
{
}
